### PR TITLE
Allow using closures as transformer (#1)

### PR DESCRIPTION
**Pull request by c00p3r**
Original Fractal package allows closures as transformers (https://fractal.thephpleague.com/transformers/)
so it would be good and useful to leave that feature
SO it for example will allow folks to transform the data using Laravel API Resource like this
```
return DataTables::eloquent($query)
            ->setTransformer(function ($item){
                return Resource::make($item)->resolve();
            })
            ->make();
```
Also, if you accept this PR, would be probably nice to update 'datatables' docs chapter ['Response > Fractal Transformer'](http://yajrabox.com/docs/laravel-datatables/master/response-fractal)

### CODE REVIEW

**Comment by c00p3r** [comment]
I'm not the only one https://github.com/yajra/laravel-datatables/issues/1863

**Comment by yajra** [comment]
Wow, love this PR. It makes the resource integration easier. Thanks a lot! ❤️ 🍻

**Comment by yajra** [comment]
Released on v1.3.0. For the docs, it's located on https://github.com/yajra/laravel-datatables-docs/blob/master/response-fractal.md. Would you mind sending a PR too? Thanks!

**Comment by c00p3r** [comment]
Wow! That was fast! Thank you too!
I'll update the datatables docs

**Pull request merged**
